package Client.GUI;

import Client.MovePanelIQ.Danhmuc;
import Client.MovePanelIQ.EventMenu;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class InterfaceIQ extends javax.swing.JFrame {

    public InterfaceIQ() {
        try {
            UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(InterfaceIQ.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        Form.interfaceIQ = this;
        this.setLocationRelativeTo(null);
        this.setTitle("KIỂM TRA IQ");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        EventMenu catchEvent = new EventMenu(pnIQ);
        ArrayList<Danhmuc> menu = new ArrayList<Danhmuc>();

        menu.add(new Danhmuc("cau1", pn1, lb1));
        menu.add(new Danhmuc("cau2", pn2, lb2));
        menu.add(new Danhmuc("cau3", pn3, lb3));
        menu.add(new Danhmuc("cau4", pn4, lb4));
        menu.add(new Danhmuc("cau5", pn5, lb5));
        menu.add(new Danhmuc("cau6", pn6, lb6));
        menu.add(new Danhmuc("cau7", pn7, lb7));
        menu.add(new Danhmuc("cau8", pn8, lb8));
        menu.add(new Danhmuc("cau9", pn9, lb9));
        menu.add(new Danhmuc("cau10", pn10, lb10));
//        menu.add(new Danhmuc("sanpham", pnsp, lbsp));
//        menu.add(new Danhmuc("loaisanpham", pnlsp, lblsp));
//        menu.add(new Danhmuc("nhanvien", pnnv, lbnv));
//        menu.add(new Danhmuc("chucvu", pncv, lbcv));
//        menu.add(new Danhmuc("khachhang", pnkh, lbkh));
//        menu.add(new Danhmuc("nhacungcap", pnncc, lbncc));
//        menu.add(new Danhmuc("hoadon", pnhd, lbhd));
//        menu.add(new Danhmuc("phieunhap", pnpn, lbpn));
//        menu.add(new Danhmuc("khuyenmai", pnkm, lbkm));
        catchEvent.setMenu(menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnIQ = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pn1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        pn2 = new javax.swing.JPanel();
        lb2 = new javax.swing.JLabel();
        pn4 = new javax.swing.JPanel();
        lb4 = new javax.swing.JLabel();
        pn5 = new javax.swing.JPanel();
        lb5 = new javax.swing.JLabel();
        pn3 = new javax.swing.JPanel();
        lb3 = new javax.swing.JLabel();
        pn6 = new javax.swing.JPanel();
        lb6 = new javax.swing.JLabel();
        pn7 = new javax.swing.JPanel();
        lb7 = new javax.swing.JLabel();
        pn8 = new javax.swing.JPanel();
        lb8 = new javax.swing.JLabel();
        pn9 = new javax.swing.JPanel();
        lb9 = new javax.swing.JLabel();
        pn10 = new javax.swing.JPanel();
        lb10 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KIỂM TRA IQ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        pnIQ.setBackground(new java.awt.Color(255, 255, 255));
        pnIQ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nhấn câu 1 để bắt đầu");

        javax.swing.GroupLayout pnIQLayout = new javax.swing.GroupLayout(pnIQ);
        pnIQ.setLayout(pnIQLayout);
        pnIQLayout.setHorizontalGroup(
            pnIQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnIQLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnIQLayout.setVerticalGroup(
            pnIQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnIQLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel2)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pn1.setBackground(new java.awt.Color(102, 204, 255));
        pn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn1MouseEntered(evt);
            }
        });

        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("Câu 1");
        lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn1Layout = new javax.swing.GroupLayout(pn1);
        pn1.setLayout(pn1Layout);
        pn1Layout.setHorizontalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lb1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pn1Layout.setVerticalGroup(
            pn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lb1)
                .addContainerGap())
        );

        pn2.setBackground(new java.awt.Color(102, 204, 255));
        pn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn2MouseClicked(evt);
            }
        });

        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb2.setText("Câu 2");

        javax.swing.GroupLayout pn2Layout = new javax.swing.GroupLayout(pn2);
        pn2.setLayout(pn2Layout);
        pn2Layout.setHorizontalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lb2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn2Layout.setVerticalGroup(
            pn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lb2)
                .addContainerGap())
        );

        pn4.setBackground(new java.awt.Color(102, 204, 255));
        pn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn4MouseClicked(evt);
            }
        });

        lb4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb4.setText("Câu 4");

        javax.swing.GroupLayout pn4Layout = new javax.swing.GroupLayout(pn4);
        pn4.setLayout(pn4Layout);
        pn4Layout.setHorizontalGroup(
            pn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lb4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn4Layout.setVerticalGroup(
            pn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lb4)
                .addContainerGap())
        );

        pn5.setBackground(new java.awt.Color(102, 204, 255));
        pn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn5MouseClicked(evt);
            }
        });

        lb5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb5.setText("Câu 5");

        javax.swing.GroupLayout pn5Layout = new javax.swing.GroupLayout(pn5);
        pn5.setLayout(pn5Layout);
        pn5Layout.setHorizontalGroup(
            pn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lb5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn5Layout.setVerticalGroup(
            pn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lb5)
                .addContainerGap())
        );

        pn3.setBackground(new java.awt.Color(102, 204, 255));
        pn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn3MouseClicked(evt);
            }
        });

        lb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb3.setText("Câu 3");

        javax.swing.GroupLayout pn3Layout = new javax.swing.GroupLayout(pn3);
        pn3.setLayout(pn3Layout);
        pn3Layout.setHorizontalGroup(
            pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lb3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn3Layout.setVerticalGroup(
            pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lb3)
                .addContainerGap())
        );

        pn6.setBackground(new java.awt.Color(102, 204, 255));
        pn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn6MouseClicked(evt);
            }
        });

        lb6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb6.setText("Câu 6");

        javax.swing.GroupLayout pn6Layout = new javax.swing.GroupLayout(pn6);
        pn6.setLayout(pn6Layout);
        pn6Layout.setHorizontalGroup(
            pn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lb6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn6Layout.setVerticalGroup(
            pn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lb6)
                .addContainerGap())
        );

        pn7.setBackground(new java.awt.Color(102, 204, 255));
        pn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn7MouseClicked(evt);
            }
        });

        lb7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb7.setText("Câu 7");

        javax.swing.GroupLayout pn7Layout = new javax.swing.GroupLayout(pn7);
        pn7.setLayout(pn7Layout);
        pn7Layout.setHorizontalGroup(
            pn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lb7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn7Layout.setVerticalGroup(
            pn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn7Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lb7)
                .addContainerGap())
        );

        pn8.setBackground(new java.awt.Color(102, 204, 255));
        pn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn8MouseClicked(evt);
            }
        });

        lb8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb8.setText("Câu 8");

        javax.swing.GroupLayout pn8Layout = new javax.swing.GroupLayout(pn8);
        pn8.setLayout(pn8Layout);
        pn8Layout.setHorizontalGroup(
            pn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lb8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn8Layout.setVerticalGroup(
            pn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn8Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lb8)
                .addContainerGap())
        );

        pn9.setBackground(new java.awt.Color(102, 204, 255));
        pn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn9MouseClicked(evt);
            }
        });

        lb9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb9.setText("Câu 9");

        javax.swing.GroupLayout pn9Layout = new javax.swing.GroupLayout(pn9);
        pn9.setLayout(pn9Layout);
        pn9Layout.setHorizontalGroup(
            pn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn9Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lb9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn9Layout.setVerticalGroup(
            pn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn9Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lb9)
                .addContainerGap())
        );

        pn10.setBackground(new java.awt.Color(102, 204, 255));
        pn10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn10MouseClicked(evt);
            }
        });

        lb10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb10.setText("Câu 10");

        javax.swing.GroupLayout pn10Layout = new javax.swing.GroupLayout(pn10);
        pn10.setLayout(pn10Layout);
        pn10Layout.setHorizontalGroup(
            pn10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lb10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn10Layout.setVerticalGroup(
            pn10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn10Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lb10)
                .addContainerGap())
        );

        btnDone.setText("Xong");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnIQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDone))
                    .addComponent(pnIQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MouseClicked
        // TODO add your handling code here:
        EventMenu catchEvent = new EventMenu(pnIQ);
        ArrayList<Danhmuc> menu = new ArrayList<Danhmuc>();

        menu.add(new Danhmuc("trangchu", pn1, lb1));
        catchEvent.setMenu(menu);
    }//GEN-LAST:event_lb1MouseClicked

    private void pn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn1MouseEntered

    private void pn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn1MouseClicked
        // TODO add your handling code here:
        pn1.setBackground(new Color(44, 62, 80));
        pn2.setBackground(new Color(1, 133, 153));
        pn3.setBackground(new Color(1, 133, 153));
        pn4.setBackground(new Color(1, 133, 153));
        pn5.setBackground(new Color(1, 133, 153));
        pn6.setBackground(new Color(1, 133, 153));
        pn7.setBackground(new Color(1, 133, 153));
        pn8.setBackground(new Color(1, 133, 153));
        pn9.setBackground(new Color(1, 133, 153));
        pn10.setBackground(new Color(1, 133, 153));
    }//GEN-LAST:event_pn1MouseClicked

    private void pn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn2MouseClicked
        // TODO add your handling code here:
        pn1.setBackground(new Color(1, 133, 153));
        pn2.setBackground(new Color(44, 62, 80));
        pn3.setBackground(new Color(1, 133, 153));
        pn4.setBackground(new Color(1, 133, 153));
        pn5.setBackground(new Color(1, 133, 153));
        pn6.setBackground(new Color(1, 133, 153));
        pn7.setBackground(new Color(1, 133, 153));
        pn8.setBackground(new Color(1, 133, 153));
        pn9.setBackground(new Color(1, 133, 153));
        pn10.setBackground(new Color(1, 133, 153));
    }//GEN-LAST:event_pn2MouseClicked

    private void pn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn3MouseClicked
        // TODO add your handling code here:
        pn1.setBackground(new Color(1, 133, 153));
        pn2.setBackground(new Color(1, 133, 153));
        pn3.setBackground(new Color(44, 62, 80));
        pn4.setBackground(new Color(1, 133, 153));
        pn5.setBackground(new Color(1, 133, 153));
        pn6.setBackground(new Color(1, 133, 153));
        pn7.setBackground(new Color(1, 133, 153));
        pn8.setBackground(new Color(1, 133, 153));
        pn9.setBackground(new Color(1, 133, 153));
        pn10.setBackground(new Color(1, 133, 153));
    }//GEN-LAST:event_pn3MouseClicked

    private void pn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn4MouseClicked
        // TODO add your handling code here:
        pn1.setBackground(new Color(1, 133, 153));
        pn2.setBackground(new Color(1, 133, 153));
        pn3.setBackground(new Color(1, 133, 153));
        pn4.setBackground(new Color(44, 62, 80));
        pn5.setBackground(new Color(1, 133, 153));
        pn6.setBackground(new Color(1, 133, 153));
        pn7.setBackground(new Color(1, 133, 153));
        pn8.setBackground(new Color(1, 133, 153));
        pn9.setBackground(new Color(1, 133, 153));
        pn10.setBackground(new Color(1, 133, 153));
    }//GEN-LAST:event_pn4MouseClicked

    private void pn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn5MouseClicked
        // TODO add your handling code here:
        pn1.setBackground(new Color(1, 133, 153));
        pn2.setBackground(new Color(1, 133, 153));
        pn3.setBackground(new Color(1, 133, 153));
        pn4.setBackground(new Color(1, 133, 153));
        pn5.setBackground(new Color(44, 62, 80));
        pn6.setBackground(new Color(1, 133, 153));
        pn7.setBackground(new Color(1, 133, 153));
        pn8.setBackground(new Color(1, 133, 153));
        pn9.setBackground(new Color(1, 133, 153));
        pn10.setBackground(new Color(1, 133, 153));
    }//GEN-LAST:event_pn5MouseClicked

    private void pn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn6MouseClicked
        // TODO add your handling code here:
        pn1.setBackground(new Color(1, 133, 153));
        pn2.setBackground(new Color(1, 133, 153));
        pn3.setBackground(new Color(1, 133, 153));
        pn4.setBackground(new Color(1, 133, 153));
        pn5.setBackground(new Color(1, 133, 153));
        pn6.setBackground(new Color(44, 62, 80));
        pn7.setBackground(new Color(1, 133, 153));
        pn8.setBackground(new Color(1, 133, 153));
        pn9.setBackground(new Color(1, 133, 153));
        pn10.setBackground(new Color(1, 133, 153));
    }//GEN-LAST:event_pn6MouseClicked

    private void pn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn7MouseClicked
        // TODO add your handling code here:
        pn1.setBackground(new Color(1, 133, 153));
        pn2.setBackground(new Color(1, 133, 153));
        pn3.setBackground(new Color(1, 133, 153));
        pn4.setBackground(new Color(1, 133, 153));
        pn5.setBackground(new Color(1, 133, 153));
        pn6.setBackground(new Color(1, 133, 153));
        pn7.setBackground(new Color(44, 62, 80));
        pn8.setBackground(new Color(1, 133, 153));
        pn9.setBackground(new Color(1, 133, 153));
        pn10.setBackground(new Color(1, 133, 153));
    }//GEN-LAST:event_pn7MouseClicked

    private void pn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn8MouseClicked
        // TODO add your handling code here:
        pn1.setBackground(new Color(1, 133, 153));
        pn2.setBackground(new Color(1, 133, 153));
        pn3.setBackground(new Color(1, 133, 153));
        pn4.setBackground(new Color(1, 133, 153));
        pn5.setBackground(new Color(1, 133, 153));
        pn6.setBackground(new Color(1, 133, 153));
        pn7.setBackground(new Color(1, 133, 153));
        pn8.setBackground(new Color(44, 62, 80));
        pn9.setBackground(new Color(1, 133, 153));
        pn10.setBackground(new Color(1, 133, 153));
    }//GEN-LAST:event_pn8MouseClicked

    private void pn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn9MouseClicked
        // TODO add your handling code here:
        pn1.setBackground(new Color(1, 133, 153));
        pn2.setBackground(new Color(1, 133, 153));
        pn3.setBackground(new Color(1, 133, 153));
        pn4.setBackground(new Color(1, 133, 153));
        pn5.setBackground(new Color(1, 133, 153));
        pn6.setBackground(new Color(1, 133, 153));
        pn7.setBackground(new Color(1, 133, 153));
        pn8.setBackground(new Color(1, 133, 153));
        pn9.setBackground(new Color(44, 62, 80));
        pn10.setBackground(new Color(1, 133, 153));
    }//GEN-LAST:event_pn9MouseClicked

    private void pn10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn10MouseClicked
        // TODO add your handling code here:
        pn1.setBackground(new Color(1, 133, 153));
        pn2.setBackground(new Color(1, 133, 153));
        pn3.setBackground(new Color(1, 133, 153));
        pn4.setBackground(new Color(1, 133, 153));
        pn5.setBackground(new Color(1, 133, 153));
        pn6.setBackground(new Color(1, 133, 153));
        pn7.setBackground(new Color(1, 133, 153));
        pn8.setBackground(new Color(1, 133, 153));
        pn9.setBackground(new Color(1, 133, 153));
        pn10.setBackground(new Color(44, 62, 80));
    }//GEN-LAST:event_pn10MouseClicked

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceIQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JPanel pn1;
    private javax.swing.JPanel pn10;
    private javax.swing.JPanel pn2;
    private javax.swing.JPanel pn3;
    private javax.swing.JPanel pn4;
    private javax.swing.JPanel pn5;
    private javax.swing.JPanel pn6;
    private javax.swing.JPanel pn7;
    private javax.swing.JPanel pn8;
    private javax.swing.JPanel pn9;
    private javax.swing.JPanel pnIQ;
    // End of variables declaration//GEN-END:variables
}
