package Client.GUI;

import Client.BUS.BUS;
import Client.BUS.MainBUS;
import Client.Status;
import Client.WorkerClient;
import Shares.DTO.NguoiDungDTO;
import Shares.ServerConfig;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {

    private final MainBUS mainBUS;
    public static boolean flag;
    DefaultTableModel model;

    public Main() {
        try {
            UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        this.setTitle("Trang chủ");
        initComponents();
        Form.main = this;
        mainBUS = new MainBUS();
        flag = true;

        lbUserName.setText(BUS.user.getTenNguoiDung());
        lbWin.setText(String.valueOf(BUS.user.getTongTranThang()));
        lbLose.setText(String.valueOf(BUS.user.getTongTran() - BUS.user.getTongTranThang()));
        lbChuoiWin.setText(String.valueOf(BUS.user.getChuoiThang()));
        lbChuoiLose.setText(String.valueOf(BUS.user.getChuoiThua()));
        lbIQ.setText(String.valueOf(BUS.user.getDiemIQ()));
        model = new DefaultTableModel();
        model = (DefaultTableModel) tblXepHang.getModel();
        model.setRowCount(0);
        // gán danh sách vô table
        getDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        pnMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        lbTime = new javax.swing.JLabel();
        btnIQ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblXepHang = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        lbXepHang = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbWin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbChuoiWin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbLose = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbChuoiLose = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbIQ = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANG CHỦ");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPlay.setBackground(new java.awt.Color(255, 255, 255));
        btnPlay.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnPlay.setText("BẮT ĐẦU");
        btnPlay.setBorder(new javax.swing.border.MatteBorder(null));
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        lbTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(lbTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnIQ.setText("Kiểm tra IQ");
        btnIQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIQActionPerformed(evt);
            }
        });

        tblXepHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Xếp hạng", "Họ tên", "Tổng điểm", "Chuỗi thắng dài nhất nhất", "Chuỗi thua dài nhất", "Tỉ lệ thắng", "Tỉ lệ thua"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblXepHang);

        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lbXepHang.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lbXepHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbXepHang.setText("BẢNG XẾP HẠNG");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Tra cứu :");

        lbUserName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbUserName.setText("UserName");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Số trận thắng :");

        lbWin.setText("1");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Chuỗi thắng :");

        lbChuoiWin.setText("0");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Số trận thua :");

        lbLose.setText("2");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Chuỗi thua :");

        lbChuoiLose.setText("0");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Điểm IQ:");

        lbIQ.setText("180");

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                        .addComponent(lbUserName)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbLose)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(lbChuoiLose)
                                .addGap(622, 622, 622))
                            .addGroup(pnMainLayout.createSequentialGroup()
                                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnMainLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbWin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbChuoiWin))
                                    .addGroup(pnMainLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbIQ)
                                        .addGap(115, 115, 115)
                                        .addComponent(lbXepHang, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btnIQ, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbWin)
                    .addComponent(jLabel4)
                    .addComponent(lbChuoiWin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbLose)
                    .addComponent(jLabel6)
                    .addComponent(lbChuoiLose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbIQ)
                    .addComponent(lbXepHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btnIQ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        // TODO add your handling code here:
        if (txtSearch.getText().trim().toLowerCase().equals("username")) {
            txtSearch.setText("");
        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        // TODO add your handling code here:
        if (txtSearch.getText().trim().toLowerCase().equals("")) {
            txtSearch.setText("Username");
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        if (btnPlay.isEnabled()) {
            if (flag) {
                playgame();
            } else {
                canclegame();
            }
        }
    }//GEN-LAST:event_btnPlayMouseClicked

    private void playgame() {
        switch (mainBUS.playgame()) {
            case Status.OK:
                if (BUS.continute()) {
                    switch (WorkerClient.status) {
                        case Status.OK:
                            flag = false;
                            btnPlay.setText("Huỷ");
                            waitting();
                            break;
                        case Status.FAILD:
                            JOptionPane.showMessageDialog(rootPane, "Gia nhập hàng chờ thất bại");
                            break;
                        case Status.LOI_KETNOI_SERVER:
                            JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối server");
                            break;
                    }
                }
                break;
            case Status.LOI_KETNOI_SERVER:
                JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối server");
                break;
        }
    }

    private void waitting() {
        TimerTask timerTask = new TimerTask() {
            int thGian = 0;
            int maxTime = ServerConfig.TIME_WAITTING_GAME;

            @Override
            public void run() {
                if (!flag && thGian < maxTime) {
                    lbTime.setText(setThoiGian(thGian++));
                } else {
                    lbTime.setText("");
                    if (thGian == maxTime) {
                        canclegame();
                        JOptionPane.showMessageDialog(rootPane, "Bạn đã thoát khỏi hàng chờ do vượt quá khoảng thời gian quy định!");
                    }
                    cancel();
                }
            }
        };
        Timer timer = new Timer("Timer");
        timer.schedule(timerTask, 0, 1000L);
    }

    private String setThoiGian(int second) {
        if (second < 60) {
            String str = "00" + second;
            str = str.substring(str.length() - 2, str.length());
            return "00:" + str;
        }
        return "01:00";
    }

    private void canclegame() {
        switch (mainBUS.canclegame()) {
            case Status.OK:
                if (BUS.continute()) {
                    switch (WorkerClient.status) {
                        case Status.OK:
                            flag = true;
                            btnPlay.setText("Bắt đầu");
                            break;
                        case Status.FAILD:
                            JOptionPane.showMessageDialog(rootPane, "Lỗi thoát hàng chờ");
                            break;
                        case Status.LOI_KETNOI_SERVER:
                            JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối server");
                            break;
                    }
                }
                break;
            case Status.LOI_KETNOI_SERVER:
                JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối server");
                break;
        }
    }

    private void btnIQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIQActionPerformed
        if (btnIQ.isEnabled()) {
            Form.newInterfaceIQ();
        }
    }//GEN-LAST:event_btnIQActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        searchUserName(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    public void getDataTable() {
        int i = 1;
        Collections.sort(BUS.users);
        BUS.userTmp = new ArrayList<NguoiDungDTO>();
        for (NguoiDungDTO nd : BUS.users) {
            double a = (double) nd.getTongTran();
            double b = (double) nd.getTongTranThang();
            double tilethang = Math.round((a / b) * 100);
            double tilethua = 100 - tilethang;
            model.addRow(new Object[]{
                i + "              ", nd.getTenNguoiDung(), nd.getTongDiem(), nd.getChuoiThangMax(), nd.getChuoiThuaMax(), tilethang + "%", tilethua + "%"
            });
            BUS.userTmp.add(new NguoiDungDTO(nd.getTenNguoiDung(), nd.getChuoiThangMax(), nd.getChuoiThuaMax(), nd.getTongTranThang(), nd.getTongTran(), nd.getTongDiem(), i));
            i++;
        }
        tblXepHang.setModel(model);
    }

    public void searchUserName(String username) {
        model.setRowCount(0);
//        Collections.sort(mainBUS.search(username.toLowerCase()));
        for (NguoiDungDTO nd : mainBUS.search(username.toLowerCase())) {
            double a = (double) nd.getTongTran();
            double b = (double) nd.getTongTranThang();
            double tilethang = Math.round((a / b) * 100);
            double tilethua = 100 - tilethang;
            model.addRow(new Object[]{
                nd.getXephang() + "              ", nd.getTenNguoiDung(), nd.getTongDiem(), nd.getChuoiThangMax(), nd.getChuoiThuaMax(), tilethang + "%", tilethua + "%"
            });
        }
        tblXepHang.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnIQ;
    public static javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbChuoiLose;
    private javax.swing.JLabel lbChuoiWin;
    public static javax.swing.JLabel lbIQ;
    private javax.swing.JLabel lbLose;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JLabel lbWin;
    private javax.swing.JLabel lbXepHang;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tblXepHang;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
