/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Client.GUI.QuestionIQ;

import Client.GUI.InterfaceIQ;
import Client.MovePanelIQ.CauDung;
import javax.swing.JOptionPane;

/**
 *
 * @author thanh
 */
public class Cau8 extends javax.swing.JPanel {
    private static String cauhoi = "cau8";
    /**
     * Creates new form Cau8
     */
    public Cau8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Cau8 = new javax.swing.JLabel();
        A = new javax.swing.JPanel();
        lbA = new javax.swing.JLabel();
        C = new javax.swing.JPanel();
        lbC = new javax.swing.JLabel();
        D = new javax.swing.JPanel();
        lbD = new javax.swing.JLabel();
        B = new javax.swing.JPanel();
        lbB = new javax.swing.JLabel();
        E = new javax.swing.JPanel();
        lbE = new javax.swing.JLabel();
        F = new javax.swing.JPanel();
        lbF = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Cau8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage8.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cau8)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cau8)
        );

        A.setBackground(new java.awt.Color(255, 255, 255));
        A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimageA8.png"))); // NOI18N
        lbA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ALayout = new javax.swing.GroupLayout(A);
        A.setLayout(ALayout);
        ALayout.setHorizontalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ALayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbA))
        );
        ALayout.setVerticalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        C.setBackground(new java.awt.Color(255, 255, 255));
        C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimageC8.png"))); // NOI18N
        lbC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CLayout = new javax.swing.GroupLayout(C);
        C.setLayout(CLayout);
        CLayout.setHorizontalGroup(
            CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbC))
        );
        CLayout.setVerticalGroup(
            CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        D.setBackground(new java.awt.Color(255, 255, 255));
        D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimageD8.png"))); // NOI18N
        lbD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DLayout = new javax.swing.GroupLayout(D);
        D.setLayout(DLayout);
        DLayout.setHorizontalGroup(
            DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbD))
        );
        DLayout.setVerticalGroup(
            DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        B.setBackground(new java.awt.Color(255, 255, 255));
        B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimageB8.png"))); // NOI18N
        lbB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BLayout = new javax.swing.GroupLayout(B);
        B.setLayout(BLayout);
        BLayout.setHorizontalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbB))
        );
        BLayout.setVerticalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        E.setBackground(new java.awt.Color(255, 255, 255));
        E.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimageE8.png"))); // NOI18N
        lbE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ELayout = new javax.swing.GroupLayout(E);
        E.setLayout(ELayout);
        ELayout.setHorizontalGroup(
            ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ELayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbE))
        );
        ELayout.setVerticalGroup(
            ELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        F.setBackground(new java.awt.Color(255, 255, 255));
        F.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimageF8.png"))); // NOI18N
        lbF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FLayout = new javax.swing.GroupLayout(F);
        F.setLayout(FLayout);
        FLayout.setHorizontalGroup(
            FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbF))
        );
        FLayout.setVerticalGroup(
            FLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAMouseClicked
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure choose answer 1 ?" );
        if(ans == 0){
            InterfaceIQ.tmp.add(new CauDung(cauhoi,1));
            JOptionPane.showMessageDialog(null, "Success");
        }
    }//GEN-LAST:event_lbAMouseClicked

    private void lbCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCMouseClicked
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure choose answer 2 ?" );
        if(ans == 0){
            InterfaceIQ.tmp.add(new CauDung(cauhoi,2));
            JOptionPane.showMessageDialog(null, "Success");
        }
    }//GEN-LAST:event_lbCMouseClicked

    private void lbEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEMouseClicked
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure choose answer 3 ?" );
        if(ans == 0){
            InterfaceIQ.tmp.add(new CauDung(cauhoi,3));
            JOptionPane.showMessageDialog(null, "Success");
        }
    }//GEN-LAST:event_lbEMouseClicked

    private void lbBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBMouseClicked
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure choose answer 4 ?" );
        if(ans == 0){
            InterfaceIQ.tmp.add(new CauDung(cauhoi,4));
            JOptionPane.showMessageDialog(null, "Success");
        }
    }//GEN-LAST:event_lbBMouseClicked

    private void lbDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDMouseClicked
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure choose answer 5 ?" );
        if(ans == 0){
            InterfaceIQ.tmp.add(new CauDung(cauhoi,5));
            JOptionPane.showMessageDialog(null, "Success");
        }
    }//GEN-LAST:event_lbDMouseClicked

    private void lbFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFMouseClicked
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure choose answer 6 ?" );
        if(ans == 0){
            InterfaceIQ.tmp.add(new CauDung(cauhoi,6));
            JOptionPane.showMessageDialog(null, "Success");
        }
    }//GEN-LAST:event_lbFMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A;
    private javax.swing.JPanel B;
    private javax.swing.JPanel C;
    private javax.swing.JLabel Cau8;
    private javax.swing.JPanel D;
    private javax.swing.JPanel E;
    private javax.swing.JPanel F;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbA;
    private javax.swing.JLabel lbB;
    private javax.swing.JLabel lbC;
    private javax.swing.JLabel lbD;
    private javax.swing.JLabel lbE;
    private javax.swing.JLabel lbF;
    // End of variables declaration//GEN-END:variables
}
